[package]
name = "rmr"
version = "0.3.0"
authors = ["bpglaser <bpglaser@gmail.com>"]
edition = "2021"

[[bin]]
name = "rmr"
path = "src/bin/main.rs"
doc = false

[dependencies]
image = "0.25.2"

[dependencies.clap]
version = "4.5.16"
features = ["derive"]
