[package]
name = "rmr"
version = "0.3.0"
authors = ["bpglaser <bpglaser@gmail.com>"]
edition = "2018"

[[bin]]
name = "rmr"
path = "src/bin/main.rs"
doc = false

[dependencies]
clap = "2.24.2"
image = "0.23.7"
